Pre-commit checks pylints tools directory

diff --git a/tools/pre-commit-checks b/tools/pre-commit-checks
--- a/tools/pre-commit-checks
+++ b/tools/pre-commit-checks
@@ -23,6 +23,13 @@ fi
 # Lint tests directory
 if ! pylint tests ; then
     echo "*** DO NOT COMMIT ***"
+    echo "Fix lint errors for tests directory (score must be perfect 10.0)"
+    exit 1
+fi
+
+# Lint tools directory
+if ! pylint tools ; then
+    echo "*** DO NOT COMMIT ***"
     echo "Fix lint errors for tools directory (score must be perfect 10.0)"
     exit 1
 fi
